# version: '3'

services:
  express_api:
    container_name: express_api
    build: ./app
    volumes:
      - ./app:/app/
    expose:
      - 5000
    ports:
      - "5000:5000"
    env_file:
      - ./app/.env
    depends_on:
      - mysql_db
    networks:
      - asgard
      - monitoring

  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    expose:
      - 3306
    env_file:
      - ./app/.env
    volumes:
      - ./data/mysql/src:/var/lib/mysql
    networks:
      - asgard

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    env_file:
      - ./app/.env
    depends_on:
      - mysql_db
    networks:
      - asgard


networks:
  asgard:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
